%%
%% mount3.hrl was generated by erpcgen (do not edit)
%% date: Dec 2 23:48:17 2012
%%
-define(MOUNTPROG, 100005).
-define(MOUNTVERS, 1).
-define(MOUNTVERS3, 3).
-define(FHSIZE3, 64).
-define(FHSIZE, 32).
-define(MNTNAMLEN, 255).
-define(MNTPATHLEN, 1024).
