%%
%% mount3_clnt was generated by erpcgen (do not edit)
%% date: Dec 2 23:48:17 2012
%%
-module(mount3_clnt).
-include("mount3.hrl").
-export([mountproc_null_1/1,mountproc_null_1/2]).
-export([mountproc_mnt_1/2,mountproc_mnt_1/3]).
-export([mountproc_dump_1/1,mountproc_dump_1/2]).
-export([mountproc_umnt_1/2,mountproc_umnt_1/3]).
-export([mountproc_umntall_1/1,mountproc_umntall_1/2]).
-export([mountproc_export_1/1,mountproc_export_1/2]).
-export([mountproc_exportall_1/1,mountproc_exportall_1/2]).
-export([mountproc_null_3/1,mountproc_null_3/2]).
-export([mountproc_mnt_3/2,mountproc_mnt_3/3]).
-export([mountproc_dump_3/1,mountproc_dump_3/2]).
-export([mountproc_umnt_3/2,mountproc_umnt_3/3]).
-export([mountproc_umntall_3/1,mountproc_umntall_3/2]).
-export([mountproc_export_3/1,mountproc_export_3/2]).

mountproc_export_3(Clnt) ->
    mountproc_export_3(Clnt, infinity).

mountproc_export_3(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 5, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = mount3_xdr:dec_exportnode(_2, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_umntall_3(Clnt) ->
    mountproc_umntall_3(Clnt, infinity).

mountproc_umntall_3(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 4, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_umnt_3(Clnt, _1) ->
    mountproc_umnt_3(Clnt, _1, infinity).

mountproc_umnt_3(Clnt, _1, Timeout) ->
    _2 = [mount3_xdr:enc_dirpath(_1)],
    case rpc_client:call(Clnt, 3, _2, Timeout) of
        {ok,_3} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_dump_3(Clnt) ->
    mountproc_dump_3(Clnt, infinity).

mountproc_dump_3(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 2, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = mount3_xdr:dec_mountbody(_2, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_mnt_3(Clnt, _1) ->
    mountproc_mnt_3(Clnt, _1, infinity).

mountproc_mnt_3(Clnt, _1, Timeout) ->
    _2 = [mount3_xdr:enc_dirpath(_1)],
    case rpc_client:call(Clnt, 1, _2, Timeout) of
        {ok,_3} ->
            {Reply,_} = mount3_xdr:dec_mountres3(_3, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_null_3(Clnt) ->
    mountproc_null_3(Clnt, infinity).

mountproc_null_3(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 0, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_exportall_1(Clnt) ->
    mountproc_exportall_1(Clnt, infinity).

mountproc_exportall_1(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 6, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = mount3_xdr:dec_exportnode(_2, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_export_1(Clnt) ->
    mountproc_export_1(Clnt, infinity).

mountproc_export_1(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 5, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = mount3_xdr:dec_exportnode(_2, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_umntall_1(Clnt) ->
    mountproc_umntall_1(Clnt, infinity).

mountproc_umntall_1(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 4, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_umnt_1(Clnt, _1) ->
    mountproc_umnt_1(Clnt, _1, infinity).

mountproc_umnt_1(Clnt, _1, Timeout) ->
    _2 = [mount3_xdr:enc_dirpath(_1)],
    case rpc_client:call(Clnt, 3, _2, Timeout) of
        {ok,_3} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_dump_1(Clnt) ->
    mountproc_dump_1(Clnt, infinity).

mountproc_dump_1(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 2, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = mount3_xdr:dec_mountbody(_2, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_mnt_1(Clnt, _1) ->
    mountproc_mnt_1(Clnt, _1, infinity).

mountproc_mnt_1(Clnt, _1, Timeout) ->
    _2 = [mount3_xdr:enc_dirpath(_1)],
    case rpc_client:call(Clnt, 1, _2, Timeout) of
        {ok,_3} ->
            {Reply,_} = mount3_xdr:dec_fhstatus(_3, 0),
            {ok,Reply};
        Error ->
            Error
    end.

mountproc_null_1(Clnt) ->
    mountproc_null_1(Clnt, infinity).

mountproc_null_1(Clnt, Timeout) ->
    _1 = [],
    case rpc_client:call(Clnt, 0, _1, Timeout) of
        {ok,_2} ->
            {Reply,_} = {void,0},
            {ok,Reply};
        Error ->
            Error
    end.
