%%
%% pmap.hrl was generated by erpcgen (do not edit)
%% date: Dec 2 23:48:14 2012
%%
-define(PMAP_PROG, 100000).
-define(PMAP_VERS, 2).
-define(IPPROTO_UDP, 17).
-define(IPPROTO_TCP, 6).
-define(PMAP_PORT, 111).
